// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A psychic reading AI agent.
 *
 * - generatePsychicReading - A function that handles the psychic reading process.
 * - GeneratePsychicReadingInput - The input type for the generatePsychicReading function.
 * - GeneratePsychicReadingOutput - The return type for the generatePsychicReading function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GeneratePsychicReadingInputSchema = z.object({
  name: z.string().describe('The name of the user.'),
  birthDate: z.string().describe('The birth date of the user (YYYY-MM-DD).'),
  personalDetails: z.string().describe('Additional personal details about the user.'),
});

export type GeneratePsychicReadingInput = z.infer<typeof GeneratePsychicReadingInputSchema>;

const GeneratePsychicReadingOutputSchema = z.object({
  reading: z.string().describe('The psychic reading for the user.'),
});

export type GeneratePsychicReadingOutput = z.infer<typeof GeneratePsychicReadingOutputSchema>;

export async function generatePsychicReading(input: GeneratePsychicReadingInput): Promise<GeneratePsychicReadingOutput> {
  return generatePsychicReadingFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generatePsychicReadingPrompt',
  input: {schema: GeneratePsychicReadingInputSchema},
  output: {schema: GeneratePsychicReadingOutputSchema},
  prompt: `You are a psychic specializing in love and relationships. Based on the user's name, birth date, and personal details, generate a psychic reading about their soulmate's personality traits and potential relationship dynamics.\n\nName: {{{name}}}\nBirth Date: {{{birthDate}}}\nPersonal Details: {{{personalDetails}}}\n\nPsychic Reading: `,
});

const generatePsychicReadingFlow = ai.defineFlow(
  {
    name: 'generatePsychicReadingFlow',
    inputSchema: GeneratePsychicReadingInputSchema,
    outputSchema: GeneratePsychicReadingOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
